name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
        with:
          cache: false
        env:
          MISE_NODE_COREPACK: true

      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn build
      - run: yarn typecheck
      - run: yarn test
